name: Hello # ワークフロー名
on: push # トリガーイベント（pushの場合，このファイルをプッシュすると起動するのではなくて，リポジトリにプッシュがあると常に起動する挙動となる）
jobs: # ジョブの定義
  hello: # ジョブID
    runs-on: ubuntu-latest # ランナー（Ubuntuで実行）
    steps: # ステップの定義
      - run: echo "Hello, world" # シェルコマンドの実行
      - uses: actions/checkout@v4 # アクションの呼び出し
